# Generated by Django 3.2 on 2021-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_pathname',
            field=models.CharField(blank=True, help_text='Eg. If you enter my-page then people will go to email-collection-app.herokuapp.com/my-page to access the page you create', max_length=40),
        ),
    ]
